services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      MSSQL_SA_PASSWORD: "SqlServer2019!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - ./DataBase:/var/opt/mssql
      # - ./DataBase:/var/opt/mssql/data
      # - ./Logs:/var/opt/mssql/log
      # - ./Secrets:/var/opt/mssql/secrets

  # mssqltools:
  #   image: mcr.microsoft.com/mssql-tools
  #   depends_on:
  #     - sqlserver
    # volumes:
    #   - ./01-BaseGeografica.sql:/tmp/01-BaseGeografica.sql
    #   - ./02-BaseGeografica.sql:/tmp/02-BaseGeografica.sql
    #   - ./init-basegeografica.sh:/tmp/init-basegeografica.sh
    # command: /bin/bash ./tmp/init-basegeografica.sh