services:
  mysqlsrv:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "MySql2019!"
      MYSQL_DATABASE: "testedb"
    command: mysqld --sql_mode="" --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./DataBase:/var/lib/mysql
    networks:
      - local-services-network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - local-services-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    depends_on:
      - mysqlsrv
    links:
      - mysqlsrv
    environment:
      PMA_HOST: mysqlsrv
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - local-services-network

networks:
  local-services-network:
    driver: bridge