version: '3'

services:
  mysqlsrv:
    image: mysql:8.0.31
    environment:
      MYSQL_ROOT_PASSWORD: "MySql2019!"
      MYSQL_DATABASE: "testedb"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /Users/rafaelfreitas/Sites/dockers/Mysql/DataBase:/var/lib/mysql
    networks:
      - local-services-network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - local-services-network

networks: 
  local-services-network:
    driver: bridge