services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks: 
      - ${NETWORK_NAME}
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    networks: 
      - ${NETWORK_NAME}
    depends_on:
      - zookeeper
    ports:
      - ${KAFKA_PORT}:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:${KAFKA_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    networks: 
      - ${NETWORK_NAME}
    depends_on:
      - kafka
    ports:
      - ${KAFDROP_PORT}:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092

  kafka-ui:
    image: provectuslabs/kafka-ui
    networks: 
      - ${NETWORK_NAME}
    container_name: kafka-ui
    ports:
      - "${KAFKA_UI_PORT}:8080"
    depends_on:
      - kafka
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092

networks: 
  ${NETWORK_NAME}:
    driver: bridge  