services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./users.acl:/usr/local/etc/redis/users.acl
    command: redis-server --appendonly yes --aclfile /usr/local/etc/redis/users.acl
    networks:
      - local-services-network
    restart: unless-stopped

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    depends_on:
      - redis
    networks:
      - local-services-network
    restart: unless-stopped

volumes:
  redis_data:
    driver: local

networks:
  local-services-network:
    driver: bridge