services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
      - ./users.acl:/usr/local/etc/redis/users.acl
    command: redis-server --appendonly yes --aclfile /usr/local/etc/redis/users.acl
    networks:
      - ${NETWORK_NAME}
    restart: unless-stopped

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "${REDIS_INSIGHT_PORT}:5540"
    depends_on:
      - redis
    networks:
      - ${NETWORK_NAME}
    restart: unless-stopped

volumes:
  redis_data:
    driver: local

networks:
  ${NETWORK_NAME}:
    driver: bridge